# Generated by Django 5.0.6 on 2024-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='birth_year',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=2013, max_length=100),
            preserve_default=False,
        ),
    ]
