# Generated by Django 5.0.6 on 2024-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team_rename_age_player_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
    ]
